name: sylph_dart_configs
description: SylphLab shared Dart configurations and guidelines.
version: 0.1.0
repository: https://github.com/sylphlab/dart
publish_to: none # This repo itself isn't a package, sub-packages might be later

environment:
  sdk: '>=3.3.0 <4.0.0'

# No dependencies needed for the root project itself yet
dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  melos: ^6.0.0 # Use latest melos version