name: Dart CI (sylphlab/dart)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK - Pin version for consistency
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.3.0' # Match pubspec.yaml constraint

      # Activate Melos
      - name: Activate Melos
        run: dart pub global activate melos ^6.0.0

      # Install dependencies using Melos bootstrap
      - name: Install Dependencies
        run: melos bootstrap

      # Verify formatting using Melos script
      - name: Verify Formatting
        run: melos run format

      # Analyze project code using Melos script
      - name: Analyze Project
        run: melos run analyze

      # Run tests using Melos script
      # Note: Coverage generation/upload might need refinement for monorepos
      - name: Run Tests
        run: melos run test

      # TODO: Add coverage generation and upload step (needs careful handling in monorepo)
      # Example (might need adjustment):
      # - name: Generate Coverage Report (Example - Needs Testing)
      #   run: |
      #     dart pub global activate coverage
      #     melos exec -- dart test --coverage=coverage --reporter=expanded # Run tests with coverage enabled
      #     # Combine coverage reports if possible (tooling might be needed)
      #     # Format the combined report
      #     # dart pub global run coverage:format_coverage --lcov --in=coverage_combined --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=packages
      #
      # - name: Upload Coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # Add CODECOV_TOKEN secret to repo
      #     files: coverage/lcov.info
      #     fail_ci_if_error: true